Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -33,9 +33,14 @@ jobs:
 
       - name: Build the Jupyter Book
         run: jupyter-book build .
+        
+      - name: Debug: List build output
+        run: ls -R _build || echo ""_build directory not found"
 
       - name: Upload built book as artifact
         uses: actions/upload-pages-artifact@v3
+        with:
+           path: _build/html
 
       - name: Deploy to GitHub Pages
         id: deployment
